### PR TITLE
Add a new xunit project for tests

### PR DESCRIPTION
**Pull request by gldraphael**
Related: https://github.com/AlexPoint/SubtitlesParser/issues/16

### CODE REVIEW

**Comment by AlexPoint** [comment]
The only unit test added is empty. Did you forget to commit your tests?

**Comment by gldraphael** [comment]
I'll continue working on this in the weekend.

**Comment by gldraphael** [comment]
I've added tests. You can run them in Visual Studio's Text Explorer Extension, or on the commandline. I've tested with .NET Core 3.0.100.

image


I've made copies of the subtitle files being tested in the console project and put the valid and invalid file in subfolders. What I have not done is check for things like corrupted %, number of items, etc. These will need to be done on a file-by-file basis.

**Comment by AlexPoint** [comment]
Thank you for this PR. It's only two tests but that just the beginning... ;)

**Comment by gldraphael** [comment]
True that. But if we have a good test-sample size, I think this should be sufficient to give enough confidence over the parsing logic.

Now that we have tests, could consider setting up CI BTW :)

**Comment by gldraphael** [comment]
image

**Pull request merged**
